module.exports = {
  'beatmaker test': function (browser) {
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer)
      .waitForElementVisible('#app', 5000)
      .assert.elementPresent('#beat-maker')
      .assert.elementPresent('.instrument-row')
      .assert.elementCount('.instrument-row', 8)
      .sendKeys('#app', 'z')
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .assert.elementPresent('.beat-column')
      .assert.elementCount('.beat-column.selected', 1)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.DOWN_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)
      .sendKeys('#app', browser.Keys.SPACE)
      .sendKeys('#app', browser.Keys.UP_ARROW)
      .sendKeys('#app', browser.Keys.RIGHT_ARROW)

      .end()
  }
}
